### ISSUE TITLE
Add to brew?

### ISSUE THREAD

**Issue by FezVrasta** [gesquive/git-user#1]
Awesome project! May you add it to Homebrew to make it easier the installation and update on Mac?

Thanks!

**Comment by gesquive** [comment]
I don't really use a mac, so I'm not entirely sure how to go about testing this. I'm willing to give it a try though.
@FezVrasta Would you be willing to help test?

**Comment by FezVrasta** [comment]
Sure I can test it.

**Comment by gesquive** [comment]
@FezVrasta I created a homebrew tap for the utility. (It seemed like the way to go.)

Can you please test by running `brew install gesquive/git/git-user`.

Let me know if you have any problems.

**Comment by FezVrasta** [comment]
Seems to work fine! Thanks
